# Generated by Django 4.2.7 on 2023-11-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='situation',
            field=models.BooleanField(default=True),
        ),
    ]
